services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: depth_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./tmp/model-weights:/app/tmp/model-weights
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    networks:
      - depth_network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: depth_frontend
    restart: unless-stopped
    ports:
      - "8080:80"  # Nginx serves on port 80 inside the container
    depends_on:
      - backend
    networks:
      - depth_network

networks:
  depth_network:
    driver: bridge
